### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by zacharyweston** [zacharyweston/codelab-sinatra-sass-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://afternoon-hamlet-45355.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-sass-intro/1) criteria:
- [x] You're building off [this mock app](https://github.com/chrisvfritz/sinatra-sass-intro-practice/archive/master.zip) (copy those files into your project directory).
- [x] The CSS in `public/stylesheets/sass/app.scss` is refactored according to [the TODO comments in the file](https://github.com/chrisvfritz/sinatra-sass-intro-practice/blob/master/public/stylesheets/sass/app.scss).
- [x] Your client has mentioned they want the page to "pop" more, with _just a hint_ of pizazz. To accomplish this, uncomment and specify override values for all of the commented-out Bootstrap variables, as well as five more you choose from [the Boostrap variables list](http://getbootstrap.com/customize/#less-variables).

**Comment by chrisvfritz** [comment]
Just the right amount of pizazz. 😜  Only two areas with room for improvement that I see:

### Selecting a class on the parent selector

This code below:

``` scss
h1, h2, h3, h4, h5, h6 {
  .text-muted {
    text-transform: uppercase;
    letter-spacing: 3px;
  }
}
```

Actually compiles to this:

``` css
h1 .text-muted, h2 .text-muted, h3 .text-muted, h4 .text-muted, h5 .text-muted, h6 .text-muted {
  text-transform: uppercase;
  letter-spacing: 3px;
}
```

Which is _slightly_ different from:

``` css
h1.text-muted, h2.text-muted, h3.text-muted, h4.text-muted, h5.text-muted, h6.text-muted {
  text-transform: uppercase;
  letter-spacing: 3px;
}
```

Instead of selecting headings _with_ that class, we're selecting elements with that class that are _inside of_ headings. [This article](http://thesassway.com/intermediate/referencing-parent-selectors-using-ampersand) can help you fix that. 😃 

### Mixin isn't using variables passed to it

In the mixin below:

``` scss
@mixin rotate($deg, $direction) {
  -webkit-transform: rotate(-3deg);
  -ms-transform: rotate(-3deg);
  transform: rotate(-3deg);
  -webkit-transform-origin: left;
  -ms-transform-origin: left;
  transform-origin: left;
}
```

we're not actually using the `$deg` and `$direction` passed to the mixin. Instead, `-3` and `left` are hardcoded in. That means if I called `@include rotate(23, center)`, I'll still get an item rotated -3 degrees with the origin on the left. See if you can figure out how to fix that. Otherwise, I'm happy to help point you in the right direction!

**Comment by chrisvfritz** [comment]
@zacharyweston Hi Zach - just checking in on this. 😃

**Comment by zacharyweston** [comment]
Hi Chris, new code has been pushed to GitHub. Would you like the Heroku app updated as well?

**Comment by chrisvfritz** [comment]
No update to Heroku necessary. 😃  The mixin still isn't _quite_ right though. Your new code:

``` scss
@mixin rotate($deg, $direction) {
  -webkit-transform: rotate(#{$deg}, #{$direction});
  -ms-transform: rotate(#{$deg}, #{$direction});
  transform: rotate(#{$deg}, #{$direction});
  -webkit-transform-origin: left;
  -ms-transform-origin: left;
  transform-origin: left;
}
```

actually produces invalid CSS, because `rotate` only takes a single argument - the degrees. Taking a look at this example mixin from the [Sass docs](http://sass-lang.com/guide):

``` scss
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
  -moz-border-radius: $radius;
  -ms-border-radius: $radius;
  border-radius: $radius;
}
```

we can also see that the crab claws (`#{}`) are unnecessary. Instead, `rotate($deg)` will work fine. 😄  Along with that change, let's also update this mixin so that `$direction` is used in place of `left`. If you're still not feeling completely sure why we're making these changes or what they do, please don't hesitate to ask further questions and I'll be happy to clarify.
